---
name: Continuous Integration

on:
  # Run on pushes to the default branch.
  push:
    branches:
      - main

  # Run on all PRs.
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

  # Support merge queues.
  merge_group:

  # Run on a schedule.
  schedule:
    - cron: "0 14 * * 1" # Every Monday at 9 in the morning CST

  # Allow running this workflow manually from the Actions tab.
  workflow_dispatch:

env:
  CI: true

permissions:
  contents: read # Needed to clone the repository

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: 📚 Git checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          submodules: recursive
          clean: true
          persist-credentials: false
          set-safe-directory: true
      - name: ⠨⠿ Install pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      - name: ⬢ Install Node
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version-file: .nvmrc
          cache: "pnpm"
      - name: 📦 Install dependencies
        run: pnpm install --frozen-lockfile
      - name: 🕵️ Merge Checks
        run: pnpm run merge-checks

  spell-check:
    name: Check Spelling
    runs-on: ubuntu-latest

    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          submodules: recursive
          clean: true
          persist-credentials: false
          set-safe-directory: true

      - name: 🪄 Spell Check Repo
        uses: crate-ci/typos@80c8a4945eec0f6d464eaf9e65ed98ef085283d1 # v1.38.1

  link-check:
    name: Check Links
    timeout-minutes: 2
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: 📚 Git checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          submodules: recursive
          clean: true
          persist-credentials: false
          set-safe-directory: true
      - name: ⚙️ Restore lychee cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      - name: 🪄 Link check
        uses: lycheeverse/lychee-action@885c65f3dc543b57c898c8099f4e08c8afd178a2 # v2.6.1
        with:
          args: --cache --max-cache-age 1d .
          token: ${{ github.token }}

  zizmor:
    name: Run zizmor
    timeout-minutes: 1
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          submodules: recursive
          clean: true
          persist-credentials: false
          set-safe-directory: true
      - name: 🌈 Run zizmor
        uses: zizmorcore/zizmor-action@e673c3917a1aef3c65c972347ed84ccd013ecda4 # v0.2.0
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
